name              'lvm'
maintainer        'Sous Chefs'
maintainer_email  'help@sous-chefs.org'
license           'Apache-2.0'
description       'Installs and manages Logical Volume Manager'
version           '5.1.0'
source_url        'https://github.com/sous-chefs/lvm'
issues_url        'https://github.com/sous-chefs/lvm/issues'
chef_version      '>= 12.15'

supports 'amazon'
supports 'centos'
supports 'fedora'
supports 'freebsd'
supports 'opensuseleap'
supports 'oracle'
supports 'redhat'
supports 'scientific'
supports 'suse'
supports 'ubuntu'
