name              'lvm'
maintainer        'Sous Chefs'
maintainer_email  'help@sous-chefs.org'
license           'Apache-2.0'
description       'Installs and manages Logical Volume Manager'
version           '6.2.6'
source_url        'https://github.com/sous-chefs/lvm'
issues_url        'https://github.com/sous-chefs/lvm/issues'
chef_version      '>= 17.0'

# Requires LVM 2.02.158+ for --reportformat json support.
# All supported distros ship LVM 2.02.166+ — see LIMITATIONS.md.
supports 'almalinux',     '>= 8.0'
supports 'amazon',        '>= 2023.0'
supports 'centos_stream', '>= 9.0'
supports 'debian',        '>= 12.0'
supports 'fedora'
supports 'opensuseleap',  '>= 15.0'
supports 'oracle',        '>= 8.0'
supports 'redhat',        '>= 8.0'
supports 'rocky',         '>= 8.0'
supports 'suse',          '>= 15.0'
supports 'ubuntu',        '>= 22.04'
