name              'lvm'
maintainer        'Sous Chefs'
maintainer_email  'help@sous-chefs.org'
license           'Apache-2.0'
description       'Installs and manages Logical Volume Manager'
version           '6.2.8'
source_url        'https://github.com/sous-chefs/lvm'
issues_url        'https://github.com/sous-chefs/lvm/issues'
chef_version      '>= 16.0'

supports 'almalinux'
supports 'amazon'
supports 'centos'
supports 'debian'
supports 'fedora'
supports 'opensuseleap'
supports 'oracle'
supports 'redhat'
supports 'rockylinux'
supports 'suse'
supports 'ubuntu'
