---
name: "Lint & Unit Test"

"on":
  pull_request:
  push:
    branches: [main]

jobs:
  lint-unit:
    uses: sous-chefs/.github/.github/workflows/lint-unit.yml@main
    permissions:
      actions: write
      checks: write
      pull-requests: write
      statuses: write
      issues: write

  integration:
    needs: lint-unit
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os:
          - opensuse-leap-15
          - amazonlinux-2023
          - fedora-latest
          - almalinux-9
          - almalinux-10
          - centos-stream-9
          - centos-stream-10
          - debian-12
          - debian-13
          - ubuntu-22.04
          - ubuntu-24.04
        suite:
          - default
          - create
          - remove
          - create-thin
          - resize
          - resize-thin
          - resize-thin-pool-meta-data
      fail-fast: false

    steps:
      - name: Check out code
        uses: actions/checkout@v6
      - name: Install Chef
        uses: sous-chefs/.github/.github/actions/install-workstation@main
      - name: test-kitchen
        uses: actionshub/test-kitchen@3.0.0
        env:
          CHEF_LICENSE: accept-no-persist
          KITCHEN_LOCAL_YAML: kitchen.dokken.yml
        with:
          suite: ${{ matrix.suite }}
          os: ${{ matrix.os }}
